// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vraqlfettiawwrhtkhyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyYXFsZmV0dGlhd3dyaHRraHlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDA2NDgsImV4cCI6MjA3NDIxNjY0OH0.IExvJtjYPvdo1hFp1ogYt2Dz4f-KmyfjD8jJ2InKiFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});